name: Java CI with Maven #Wie heißt die Action?

on: #Wann löst Action aus?
  push:


jobs: #Was soll passieren?
  build:

    runs-on: ubuntu-latest #Worauf läufst du?

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
